### PR TITLE
Fix de-duplication and use list for worklist

### LINKED ISSUE #2: Performance: should the worklist be a list?
I would need to be tested (maybe you've done so already), but I think that it may be be more efficient for the worklist to be a list. It probably is the right choice to have an `IntSet` for the loop, but within the datastructure, I would probably keep a list.

Then use (pseudo-code) `IntSet.fromList (map canonicalize worklist)` to generate the set.

Because of laziness, this isn't very different (an unevaluated sequence of `insert` is basically a list). But a list gives the opportunity of keeping the list in normal form, which I expect to be more compact. I don't know, it's just a thought.

### PR DESCRIPTION
**Pull request by alt-romes**
Closes #2 

We were previously using a Map for the worklist, and the deduplication
step wasn't being done correctly. This came to be from historic changes
to the representations that ultimately led to deduplication being
overlooked.

The performance significantly improves with these changes.

I think the classes parents representation was also improved. We use `SList` instead of just list because we need a O(1) size function

### CODE REVIEW

**Comment by alt-romes** [comment]
@aspiwack if you could add a drive-by comment on whether everything looks alright/this is what you had in mind/performance insights on this.

Anyway, it's already improved the performance significantly.
We can run all individual unit tests under 0.10 seconds now, while before a couple took ~0.15 seconds

Thanks!

File: src/Data/Equality/Graph/Classes.hs [hunk 1]
```diff
@@ -27,9 +29,9 @@ data EClass l = EClass
     { eClassId      :: {-# UNPACK #-} !ClassId -- ^ E-class identifier
     , eClassNodes   :: !(S.Set (ENode l))      -- ^ E-nodes in this class
     , eClassData    :: Domain l                -- ^ The analysis data associated with this eclass.
-    , eClassParents :: !(NodeMap l ClassId)    -- ^ E-nodes which are parents of this e-class and their corresponding e-class ids. We found a mapping from nodes to e-class ids a better representation than @[(ENode l, ClassId)]@, and we get de-duplication built-in.
+    , eClassParents :: !(SList (ClassId, ENode l))   -- ^ E-nodes which are parents of this e-class and their corresponding e-class ids.
```
Comment (aspiwack) [inline src/Data/Equality/Graph/Classes.hs:32]: I'm curious what the length is used for. Is it really worth an extra indirection?

Are we going to append this list to the worklist when we merge this class? Then maybe we would like a data structure that appends better? On the other hand, we do have to traverse the whole structure anyway for deduping, so probably it doesn't matter. This requires a finer understanding of the data structure than I have :slightly_smiling_face: .

File: src/Data/Equality/Utils/SizedList.hs [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+  foldMap f  ( SList l _) = foldMap f l
+  foldMap' f ( SList l _) = foldMap' f l
+  foldr f b  ( SList l _) = foldr f b l
+  foldr' f b ( SList l _) = foldr' f b l
+  foldl f b  ( SList l _) = foldl f b l
+  foldl' f b ( SList l _) = foldl' f b l
+  foldr1 f   ( SList l _) = foldr1 f l
+  foldl1 f   ( SList l _) = foldl1 f l
+  toList     ( SList l _) = l
+  null       ( SList l _) = null l
```
Comment (aspiwack) [inline src/Data/Equality/Utils/SizedList.hs:37]: Make sure to use the `null` from `Data.List`. It's going to be a tiny bit faster.

File: src/Data/Equality/Graph.hs [hunk 3]
```diff
@@ -149,7 +153,7 @@ merge a b egr0 =
 
            -- Leader is the class with more parents
            (leader, leader_class, sub, sub_class) =
-               if (sizeNM (class_a^._parents)) < (sizeNM (class_b^._parents))
+               if sizeSL (class_a^._parents) < sizeSL (class_b^._parents)
```
Comment (aspiwack) [inline src/Data/Equality/Graph.hs:156]: Ah, this is the reason for the cached size. Is this a typical criterion for choosing the head of the merge? I've never used that one. In Egg I would have imagined using the representative with the best grade (as specified by the user) as the canonical representative.

**Review by aspiwack — APPROVED** [review]
This looks good. A few random comments below if they may help.

**Comment by aspiwack** [comment]
Something else that could be experimented is to force the entire list (rather than just the head) after a `nub`. It may be better, or it may be worse.

File: src/Data/Equality/Graph.hs (hunk 3 above)
Comment (alt-romes) [reply src/Data/Equality/Graph.hs:156]: :-) https://github.com/egraphs-good/egg/blob/e19a18f60a6f1d3f5c466b37c0fe4d3cd69e550e/src/egraph.rs#L738-L750

Comment (aspiwack) [reply src/Data/Equality/Graph.hs:156]: Indeed.

Thinking back, since we constantly traverse this list for canonization/nubbing. It's ok to compute the length at the same time.

In fact, I realise as I'm writing this that the fact that the length is strict makes sure that the spine of the list, at least, is forced. It's probably a good thing.

**Comment by alt-romes** [comment]
1. I added a commit that removes the cost centers which boosts performance as well

> Something else that could be experimented is to force the entire list (rather than just the head) after a `nub`. It may be better, or it may be worse.

After experimenting I would say it makes no difference other than then having `(..., NFData1 l) => Language l` which is undesirable.

> Are we going to append this list to the worklist when we merge this class? Then maybe we would like a data structure that appends better? On the other hand, we do have to traverse the whole structure anyway for deduping, so probably it doesn't matter. This requires a finer understanding of the data structure than I have 🙂 .

I tried both Seq and Set. Honestly, the benchmarks aren't fine grained enough to notice the difference. They kind of all perform the same, with the simple `SizedList` performing just so very slightly better.

They suffer from different things and perhaps it's too late in the night for me to figure it out.

However, having the main worklist be anything other than a list resulted in performance decrease. Which meant the O(log n) concat structures had to be converted to a list before appending to the worklist. I did, however, use the same representation for the *analysis* worklist as for the class parents -- and the concat load seems to be heavier for the analysis worklist. But in the end I don't think it makes a difference, and the places where the O(n) `toList` showed up scared me a bit.

Perhaps we can try this again later.

Overall, this patch makes performance much better! It also makes everything a bit simpler by having worklists be lists and e-class parents being just lists with a cached size (which makes their `toList`O(1)).

@aspiwack I think we can merge this now and come to performance later again. I'd rather go back to profiling to figure this out later correctly

**Comment by aspiwack** [comment]
> @aspiwack I think we can merge this now and come to performance later again. I'd rather go back to profiling to figure this out later correctly

Yes.
